### ISSUE TITLE
Crash after updating mobile core to 2.0.0

### ISSUE THREAD

**Issue by emartynov** [Adobe-Marketing-Cloud/acp-sdks#680]
Hi people,

We are getting crashes after the updating the core to 2.0.0:
```
java.lang.NoSuchMethodError: No static method getCore()Lcom/adobe/marketing/mobile/Core; in class Lcom/adobe/marketing/mobile/MobileCore; or its super classes (declaration of 'com.adobe.marketing.mobile.MobileCore' appears in /data/app/~~eAcirOy6kbYc_UpoEmuzDg==/app.staging-KAoLSHvvpLHNMy1NrMLkKg==/base.apk)
                 	at com.adobe.marketing.mobile.Analytics.I(Unknown Source:0)
                 	at package.Application.onCreate(Unknown Source:815)
```

**Comment by yangyansong-adbe** [comment]
@emartynov  
It looks like you included Core 2.0.0 and Analytics 1.x builds in your Android app. The Android SDK 2.0 are not compatible with the 1.x builds, you can try it later once we release Analytics 2.0.0 build. 

Thanks,
Yansong

**Comment by emartynov** [comment]
We also use `Assurance`, `Identity`, etc. And all of them are 2.0.0 now. Our automatic version update picked up new existing versions, which broke since Analytics is not yet updated.

**Comment by yangyansong-adbe** [comment]
We're working on releasing several 2.0 builds out in the next few days, including Analytics 2.0.0. Since this is a major version upgrade, we don't support the mixed use of 1.x SDKs and 2.0 SDKs.  Can you modify the version update scripts/tools to skip downloading the 2.0 SDKs for now? We will publish release notes for 2.0 SDKs soon, I'd recommend starting to use SDK 2.0 after that. Sorry for any inconvenience caused. 

Thanks,
Yansong

**Comment by yangyansong-adbe** [comment]
@emartynov The Android SDK 2.0 is ready to use. For more details, please see the release notes: https://developer.adobe.com/client-sdks/documentation/release-notes/#february-23-2023

Thanks,
Yansong
